backend:
  name: github
  repo: diagram-chasing/website
  skip_ci: true
media_folder: "src/content/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: true,
        }
      - {
          label: "Base URL",
          name: "base_url",
          widget: "string",
          required: false,
        }
      - { label: "Slug", name: "slug", widget: "string", required: true }
      - {
          label: "Published",
          name: "published",
          widget: "boolean",
          default: true,
        }
      - {
          label: "Featured Image",
          name: "image",
          widget: "image",
          required: true,
        }
      - {
          label: "Gallery Images",
          name: "gallery",
          widget: "list",
          required: false,
          max: 4,
          field: { 
            label: "Image", 
            name: "image", 
            widget: "image" 
          },
          hint: "Optional additional images for the project (max 4)"
        }
      - {
          label: "Type",
          name: "type",
          widget: "select",
          options: ["interactive", "article", "stories"],
          required: true,
        }
      - { label: "Date", name: "date", widget: "datetime", required: true }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          allow_add: true,
          field: { label: "Tag", name: "tag", widget: "string" },
        }
      - {
          label: "Authors",
          name: "authors",
          widget: "list",
          allow_add: true,
          field: { label: "Author Slug", name: "author", widget: "string" },
        }
      - {
          label: "Code Repository",
          name: "code",
          widget: "string",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown", required: false }

  - name: "authors"
    label: "Authors"
    folder: "src/content/authors"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    fields:
      - { label: "Name", name: "name", widget: "string", required: true }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: true,
        }
      - { label: "Slug", name: "slug", widget: "string", required: true }
      - { label: "Image", name: "image", widget: "image", required: false }
      - {
          label: "Links",
          name: "links",
          widget: "object",
          required: false,
          fields:
            [
              {
                label: "GitHub",
                name: "github",
                widget: "string",
                required: false,
              },
              {
                label: "Twitter",
                name: "twitter",
                widget: "string",
                required: false,
              },
              {
                label: "Bluesky",
                name: "bluesky",
                widget: "string",
                required: false,
              },
              {
                label: "Website",
                name: "website",
                widget: "string",
                required: false,
              },
              {
                label: "Instagram",
                name: "instagram",
                widget: "string",
                required: false,
              },
            ],
        }

  - name: "ideas"
    label: "Ideas"
    files:
      - name: "ideas"
        label: "Project Ideas"
        file: "src/content/ideas.md"
        format: "frontmatter"
        fields:
          - {
              label: "Title",
              name: "title",
              widget: "string",
              default: "Project Ideas",
            }
          - {
              label: "Ideas",
              name: "ideas",
              widget: "list",
              fields:
                [
                  {
                    label: "Date",
                    name: "date",
                    widget: "date",
                    format: "YYYY-MM-DD",
                  },
                  { label: "Pitch", name: "pitch", widget: "string" },
                  { label: "Originator", name: "originator", widget: "string" },
                  { label: "Description", name: "description", widget: "text" },
                  {
                    label: "Data Source",
                    name: "data",
                    widget: "string",
                    required: false,
                  },
                  {
                    label: "Note",
                    name: "note_text",
                    widget: "string",
                    required: false,
                  },
                  {
                    label: "Show on Page",
                    name: "show_on_page",
                    widget: "boolean",
                    default: false,
                  },
                  {
                    label: "Status",
                    name: "status",
                    widget: "select",
                    options: ["", "WIP", "PUBLISHED"],
                    required: false,
                  },
                ],
            }
